### ISSUE TITLE
You can use combo of "partition", "with_index", "even?" and "flatten"

### ISSUE THREAD

**Issue by Kashoid23** [MRAndrd/RubyHW#1]
Tomorrow I will explain how it works in more detail, you can read about the methods here:

https://apidock.com/ruby/Enumerable/partition
https://apidock.com/ruby/Enumerator/with_index
https://apidock.com/ruby/Integer/even%3F
https://apidock.com/ruby/Array/flatten

`(A.partition.with_index { |index| index.even? }).flatten`

for

https://github.com/MRAndrd/RubyHW/blob/b7344a24fad9b00b10f785aba096a93ece882d9f/HW1/tasks.rb#L1

**Comment by MRAndrd** [comment]
@Kashoid23 Updated in the last commit
