### ISSUE TITLE
Prefer string interpolation to string concatenation.

### ISSUE THREAD

**Issue by Kashoid23** [MRAndrd/RubyHW#10]
http://ruby.qkspace.com/ruby-chto-oznachaet-konstruktsiya-interpolyatsiya

FE:

`"Для ознайомлення з можливостями контактування з #{@name} введи help"`

instead of:

`'Для ознайомлення з можливостями контактування з ' + @name + ' введи help' `

https://github.com/MRAndrd/RubyHW/blob/84f2ff31b1578b3d8fff0129a87c04b69960163c/HW2/Cthulhumagochi/Cthulhu.rb#L18

**Comment by MRAndrd** [comment]
@Kashoid23 fixed in latest commit
