### ISSUE TITLE
Use self-assignment shorthand +=

### ISSUE THREAD

**Issue by Kashoid23** [MRAndrd/RubyHW#12]
https://rtfm.co.ua/books-translations/kus-ruby-s-nulya/ruby-s-nulya-chast-4-operatory/

FE:

`@stuffInIntestine += 1`

instead of:

`@stuffInIntestine = @stuffInIntestine + 1`

https://github.com/MRAndrd/RubyHW/blob/84f2ff31b1578b3d8fff0129a87c04b69960163c/HW2/Cthulhumagochi/Cthulhu.rb#L212

**Comment by MRAndrd** [comment]
@Kashoid23 fixed in latest commit
