### ISSUE TITLE
Wrong result

### ISSUE THREAD

**Issue by Kashoid23** [MRAndrd/RubyHW#2]
It is not necessary to specify indexes 1 and 8 directly as it is directly dependent. You will have to change these indexes each time when you change the array.

Also the result of execution of your program is not correct
```
irb(main):127:0> array.each_with_index.map { |e,i| e + array[0] if i >= 1 && i <= 8 && e%2 == 0}
=> [nil, 3, nil, 5, nil, 7, nil, 9, nil, nil]
```
should be
`=> [1, 18, 3, 20, 5, 22, 7, 24, 9, 26]`

We can implement this in another way - through the condition (but need to recheck).

`A.map { |element| element.even? && (element != A[0] && element != A[-1]) ? element + A.first : element }`

We check each element from the array one by one with iterator `map`

`element.even? &&` - if current element even and 
`(element != A[0] && element != A[-1])` - current element not equal to first element in array and current element not equal to last element in array
`?` - then
`element + A.first` - current element plus first element in array
`:` - else
`element` - return current element

If you have any questions tomorrow I will explain in more detail

https://github.com/MRAndrd/RubyHW/blob/b7344a24fad9b00b10f785aba096a93ece882d9f/HW1/tasks.rb#L13

**Comment by MRAndrd** [comment]
@Kashoid23 Updated in the last commit
