### ISSUE TITLE
You can use method "index"

### ISSUE THREAD

**Issue by Kashoid23** [MRAndrd/RubyHW#3]
In such case, you return element but not index

```
min = array.min
arr = array.find_all { |e| e == min }
arr.first
```
better to use method index for that

`arr.index(arr.min)`

https://apidock.com/ruby/Array/index

`arr.min` - will return min element
`arr.index(...)` - will return index of passed element

for

https://github.com/MRAndrd/RubyHW/blob/b7344a24fad9b00b10f785aba096a93ece882d9f/HW1/tasks.rb#L205
https://github.com/MRAndrd/RubyHW/blob/b7344a24fad9b00b10f785aba096a93ece882d9f/HW1/tasks.rb#L214

**Comment by MRAndrd** [comment]
@Kashoid23 Updated in the last commit
