### ISSUE TITLE
Better to use "rindex" method

### ISSUE THREAD

**Issue by Kashoid23** [MRAndrd/RubyHW#4]
https://apidock.com/ruby/Array/rindex

for

https://github.com/MRAndrd/RubyHW/blob/b7344a24fad9b00b10f785aba096a93ece882d9f/HW1/tasks.rb#L223
https://github.com/MRAndrd/RubyHW/blob/b7344a24fad9b00b10f785aba096a93ece882d9f/HW1/tasks.rb#L232

**Comment by MRAndrd** [comment]
@Kashoid23 Updated in the last commit
