### ISSUE TITLE
Need to reconfigure the code editor

### ISSUE THREAD

**Issue by Kashoid23** [MRAndrd/RubyHW#6]
It looks like your editor uses tabs instead of spaces.
Use 2 spaces for indentation instead of tabs, please.

https://github.com/MRAndrd/RubyHW/blob/84f2ff31b1578b3d8fff0129a87c04b69960163c/HW2/Cthulhumagochi/Cthulhu.rb

**Comment by MRAndrd** [comment]
@Kashoid23 fixed in latest commit
