### ISSUE TITLE
Need to standardize the code

### ISSUE THREAD

**Issue by Kashoid23** [MRAndrd/RubyHW#7]
Please format the code like in https://github.com/rubocop/ruby-style-guide, as the code is currently unreadable

https://github.com/MRAndrd/RubyHW/blob/84f2ff31b1578b3d8fff0129a87c04b69960163c/HW2/Cthulhumagochi/Cthulhu.rb

**Comment by MRAndrd** [comment]
@Kashoid23 fixed in latest commit
